name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'  # 4:15 AM UTC daily
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Append timestamp to log
        run: echo "TDSFU Daily run: $(date -u) TDSFU" >> daily-log.txt

      - name: Commit and Push
        run: |
          git add daily-log.txt
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto commit at $(date -u)"
          git push
