#@@ -2,30 +2,26 @@ 
name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Ensure GitHub Actions can push changes
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #- name: Configure Git (23f3003124@ds.study.iitm.ac.in)
        #run: |
         # git config --global user.name "GitHub Action"
         # git config --global user.email "23f3003124@ds.study.iitm.ac.in"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ allows push access

      - name: Make a Change
      - name: Commit step - 23f3003124@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > last_run.txt  # Always modify the file
          echo "TDSFU Daily run: $(date -u) TDSFU" >> daily-log.txt

      - name: Commit and Push Changes
      - name: Git Commit and Push
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit at $(date)" || echo "No changes to commit"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Auto commit at $(date -u)" || echo "No changes to commit"
          git push
